const fs = require('fs');

const path = 'src/TrackerApp.tsx';
let content = fs.readFileSync(path, 'utf-8');

const tTarget = /'MASTERS_SEALED_TP_FOLDER': \[\s*'SEALED_ULTRA_BOUT_TP_V3'\s*\],/s;
const tRepl = `'MASTERS_SEALED_TP_FOLDER': [
    'SEALED_TP01', 'SEALED_TP02', 'SEALED_TP03', 'SEALED_TP04', 'SEALED_TP05_2019', 'SEALED_TP06', 'SEALED_TP07', 'SEALED_TP08', 'SEALED_TP09', 'SEALED_EX_TP', 'SEALED_TP_UW1', 'SEALED_TP_UW2', 'SEALED_TP_UW3', 'SEALED_TP_UW4', 'SEALED_TP_UW5', 'SEALED_TP_UW6', 'SEALED_TP_UW7', 'SEALED_TP_UW8', 'SEALED_ZENKAI_START_PACK', 'SEALED_ZENKAI_TP_V1', 'SEALED_ZENKAI_SERIES_PACK_V1', 'SEALED_ZENKAI_TP_V2', 'SEALED_Z03_DASH_PACK', 'SEALED_ZENKAI_TP_V3', 'SEALED_ZENKAI_TP_V4', 'SEALED_ZENKAI_TP_V5', 'SEALED_ZENKAI_TP_V6', 'SEALED_ZENKAI_TP_V7', 'SEALED_DELUXE_PACK_2024_V1', 'SEALED_ZENKAI_TP_V8', 'SEALED_DELUXE_PACK_2024_V2', 'SEALED_ZENKAI_TP_V9', 'SEALED_ZENKAI_TP_V10', 'SEALED_DELUXE_PACK_2025_V1', 'SEALED_ZENKAI_TP_V11', 'SEALED_ZENKAI_TP_V12', 'SEALED_DELUXE_PACK_2025_V2', 'SEALED_ULTRA_BOUT_TP_V13', 'SEALED_ULTRA_BOUT_TP_V1', 'SEALED_DELUXE_PACK_2026_V1', 'SEALED_DELUXE_PACK_2026_V2', 'SEALED_ULTRA_BOUT_TP_V2', 'SEALED_ULTRA_BOUT_TP_V3'
  ],`;

const eTarget = /'MASTERS_SEALED_EP_FOLDER': \[\s*'SEALED_EVENT_PACK_19'\s*\],/s;
const eRepl = `'MASTERS_SEALED_EP_FOLDER': [
    'SEALED_EVENT_PACK_01', 'SEALED_EVENT_PACK_02', 'SEALED_EVENT_PACK_03', 'SEALED_EVENT_PACK_04', 'SEALED_EVENT_PACK_05', 'SEALED_EVENT_PACK_06', 'SEALED_EVENT_PACK_07', 'SEALED_EVENT_PACK_08', 'SEALED_EVENT_PACK_09', 'SEALED_EVENT_PACK_10', 'SEALED_EVENT_PACK_11', 'SEALED_EVENT_PACK_12', 'SEALED_EVENT_PACK_13', 'SEALED_EVENT_PACK_14', 'SEALED_EVENT_PACK_15', 'SEALED_EVENT_PACK_16', 'SEALED_EVENT_PACK_17', 'SEALED_EVENT_PACK_18', 'SEALED_EVENT_PACK_19'
  ],`;

const cTarget = /'MASTERS_SEALED_CHAMPIONSHIP_FOLDER': \[\s*'SEALED_CHAMPIONSHIP_2024_ZENKAI'\s*\],/s;
const cRepl = `'MASTERS_SEALED_CHAMPIONSHIP_FOLDER': [
    'SEALED_CHAMPIONSHIP_2018', 'SEALED_CHAMPIONSHIP_2019', 'SEALED_CHAMPIONSHIP_2020_V1', 'SEALED_CHAMPIONSHIP_2020_V2', 'SEALED_CHAMPIONSHIP_2021_V1', 'SEALED_CHAMPIONSHIP_2021_V2', 'SEALED_CHAMPIONSHIP_2021_V3', 'SEALED_CHAMPIONSHIP_2022_V1', 'SEALED_CHAMPIONSHIP_2022_V2', 'SEALED_CHAMPIONSHIP_2022_V3', 'SEALED_CHAMPIONSHIP_2022_CEL', 'SEALED_CHAMPIONSHIP_2022_FP', 'SEALED_CHAMPIONSHIP_2022_ZS', 'SEALED_CHAMPIONSHIP_2023_CEL', 'SEALED_CHAMPIONSHIP_2023_ZENKAI', 'SEALED_CHAMPIONSHIP_2024_FINALS', 'SEALED_CHAMPIONSHIP_2024_ZENKAI', 'SEALED_CHAMPIONSHIP_PACS_2026_V2'
  ],`;

const pTarget = /'MASTERS_SEALED_PB_FOLDER': \[\s*'SEALED_PB03'\s*\],/s;
const pRepl = `'MASTERS_SEALED_PB_FOLDER': [
    'SEALED_PB01', 'SEALED_PB02', 'SEALED_PB03'
  ],`;

if (content.match(tTarget)) { content = content.replace(tTarget, tRepl); console.log('TP fixed'); }
if (content.match(eTarget)) { content = content.replace(eTarget, eRepl); console.log('EP fixed'); }
if (content.match(cTarget)) { content = content.replace(cTarget, cRepl); console.log('CHAMP fixed'); }
if (content.match(pTarget)) { content = content.replace(pTarget, pRepl); console.log('PB fixed'); }

fs.writeFileSync(path, content, 'utf-8');
